# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'AIMF_APP' do
  pod 'AppCenter/Crashes', '~> 3.0.0'
  pod 'AppCenter/Analytics', '~> 3.0.0'
  pod 'AppCenterReactNativeShared', '~> 3.0.0'
  # Comment the next line if you don't want to use dynamic frameworks
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Firebase/Firestore'

  # Pods for AIMF_APP

end

target 'AIMF_APP-tvOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AIMF_APP-tvOS


end
